services:
  mongodb:
    container_name: mongo
    image: 'bitnami/mongodb:8.0'
    restart: always
    ports:
      - '27017:27017'
    networks:
      - backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 20s
      retries: 5
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
  api:
    build: .
    container_name: api
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/v1/ping"]
      interval: 30s
      timeout: 20s
      retries: 5
    networks:
      - backend
    environment:
      MONGODB_URL: ${MONGODB_URL}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}

networks:
  backend:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
